apiVersion: v1
kind: Service
metadata:
  name: pilot-{{bot_id}}-service
spec:
  selector:
    app: pilot-{{bot_id}}
  ports:
    - name: web
      protocol: TCP
      port: 5005
      targetPort: 5005
    - name: action
      protocol: TCP
      port: 5055
      targetPort: 5055
