apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{workflow_id}}
spec:
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterSuccess: 600
    secondsAfterFailure: 600
  entrypoint: pilot
  templates:
    - name: pilot
      container:
        image: ccr.ccs.tencentyun.com/megalab/pilot:2
        command: [ "/bin/bash" ]
        args:
          - -c
          - |
            python ops_pilot_cli.py 
            python ops_pilot_cli.py download_train_data
            python ops_pilot_cli.py unzip_train_data
            rasa train --domain ./data/data --data ./data/data -c ./data/config.yml --fixed-model-name ops-pilot
            python ops_pilot_cli.py upload_train_model
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: MUNCHKIN_BOT_ID
            value: "{{bot_id}}"
          - name: MUNCHKIN_API_KEY
            value: ""
          - name: MUNCHKIN_BASE_URL
            value: http://munchkin.ops-pilot:8000
