apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: train-pilot-{{bot_id}}
  namespace: argo
spec:
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterSuccess: 600
    secondsAfterFailure: 600
  entrypoint: pilot
  templates:
    - name: pilot
      container:
        image: ccr.ccs.tencentyun.com/megalab/pilot:2
        command: [ "/bin/bash", "-c" ]
        args: |
          ps -ef|wc -l  &&
          ps -ef &&
          echo $BOT_ID
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: BOT_ID
            value: {{bot_id}}
