apiVersion: apps/v1
kind: Deployment
metadata:
  name: bce-embed-server
  namespace: ops-pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bce-embed-server
  template:
    metadata:
      labels:
        app: bce-embed-server
    spec:
      containers:
        - name: bce-embed-server
          image: ccr.ccs.tencentyun.com/megalab/bce-embed-server
          ports:
            - containerPort: 8102
---
apiVersion: v1
kind: Service
metadata:
  name: bce-embed-server
  namespace: ops-pilot
spec:
  selector:
    app: bce-embed-server
  ports:
    - protocol: TCP
      port: 8102
      targetPort: 8102
