apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
  namespace: ops-pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
        - name: fast-embed-server
          image: ccr.ccs.tencentyun.com/megalab/chat-server
          ports:
            - containerPort: 8105
---
apiVersion: v1
kind: Service
metadata:
  name: chat-server
  namespace: ops-pilot
spec:
  selector:
    app: chat-server
  ports:
    - protocol: TCP
      port: 8105
      targetPort: 8105
