apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunk-server
  namespace: ops-pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chunk-server
  template:
    metadata:
      labels:
        app: chunk-server
    spec:
      containers:
        - name: fast-embed-server
          image: ccr.ccs.tencentyun.com/megalab/chunk-server
          ports:
            - containerPort: 8104
---
apiVersion: v1
kind: Service
metadata:
  name: chunk-server
  namespace: ops-pilot
spec:
  selector:
    app: chunk-server
  ports:
    - protocol: TCP
      port: 8104
      targetPort: 8104