apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-embed-server-zh
  namespace: ops-pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-embed-server-zh
  template:
    metadata:
      labels:
        app: fast-embed-server-zh
    spec:
      containers:
        - name: fast-embed-server
          image: ccr.ccs.tencentyun.com/megalab/fast-embed-server
          env:
            - name: MODEL_NAME
              value: "BAAI/bge-small-zh-v1.5"
          ports:
            - containerPort: 8101
---
apiVersion: v1
kind: Service
metadata:
  name: fast-embed-server-zh
  namespace: ops-pilot
spec:
  selector:
    app: fast-embed-server-zh
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
