apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-server
  namespace: ops-pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-server
  template:
    metadata:
      labels:
        app: ocr-server
    spec:
      containers:
        - name: ocr-server
          image: ccr.ccs.tencentyun.com/megalab/ocr-server
          ports:
            - containerPort: 8109
          env:
            - name: AZURE_OCR_ENDPOINT
              value: ""
            - name: AZURE_OCR_KEY
              value: "
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-server
  namespace: ops-pilot
spec:
  selector:
    app: ocr-server
  ports:
    - protocol: TCP
      port: 8109
      targetPort: 8109
