apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-server
  namespace: ops-pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-server
  template:
    metadata:
      labels:
        app: rag-server
    spec:
      containers:
        - name: rag-server
          image: ccr.ccs.tencentyun.com/megalab/rag-server
          ports:
            - containerPort: 8106
---
apiVersion: v1
kind: Service
metadata:
  name: rag-server
  namespace: ops-pilot
spec:
  selector:
    app: rag-server
  ports:
    - protocol: TCP
      port: 8106
      targetPort: 8106
