version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      DB_SCHEMA: ${POSTGRES_DB_SCHEMA}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/postgres
      - ./conf/postgres/initdb:/docker-entrypoint-initdb.d
    restart: always

volumes:
  postgres-data: